const types = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  AUTH_CLEAR: 'AUTH_CLEAR',

  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_FAILURE: 'REGISTER_FAILURE',

  DASHBOARD_REQUEST: 'DASHBOARD_REQUEST',
  DASHBOARD_SUCCESS: 'DASHBOARD_SUCCESS',
  DASHBOARD_FAILURE: 'DASHBOARD_FAILURE',
  DASHBOARD_CLEAR: 'DASHBOARD_CLEAR:',
  SET_HINDSIGHT: 'SET_HINDSIGHT',
  SET_EMPLOYEES: 'SET_EMPLOYEES',
  SET_ACTIONS: 'SET_ACTIONS',

  SET_HINDSIGHTS_PENDING: 'SET_HINDSIGHTS_PENDING',
  REMOVE_HINDSIGHT_PENDING: 'REMOVE_HINDSIGHT_PENDING',
  SET_CURRENT_HINDSIGHT: 'SET_CURRENT_HINDSIGHT',
  REMOVE_CURRENT_HINDSIGHT: 'REMOVE_CURRENT_HINDSIGHT',
  SET_CURRENT_ACTIONS: 'SET_CURRENT_ACTIONS',
  STEP_CLEAR: 'STEP_CLEAR',

  TOOGLE_THEME: 'TOOGLE_THEME',
  PERSIST_REHYDRATE: 'persist/REHYDRATE',
};

export default types;
